[package]
name = "rshark"
version = "0.0.1"
authors = ["Jonathan Anderson <jonathan.anderson@mun.ca>"]

[dependencies]
byteorder = "0.3.11"
docopt = "0.6.70"
pcap = "0.4.2"
rustc-serialize="*"

[[bin]]
doc = false
name = "rshark"
